name: 'Python Setup'
description: 'Prepara el repositorio, configura Python 3.12, crea un entorno virtual e instala las dependencias de requirements.txt'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Crear entorno virtual e instalar dependencias
      shell: bash
      run: |
        python -m venv .venv
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        .venv/bin/pip install -r requirements.txt
